name: build_release

on: workflow_dispatch

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run build task
        run: ./gradlew build
      - name: Upload release build as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ottaku-bot-release.tar
          path: build/distributions/com.example.stocks-aggregator-0.0.1.tar
          retention-days: 2