name: deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run build task
        run: ./gradlew build
      - name: Upload release build as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ottaku-bot-release.tar
          path: build/distributions/com.example.stocks-aggregator-0.0.1.tar
          retention-days: 2

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v3
        with:
          name: ottaku-bot-release.tar
      - name: Upload release artifact to production environment
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          passphrase: ${{ secrets.PROD_SSH_PASSPHRASE }}
          source: com.example.stocks-aggregator-0.0.1.tar
          target: "OttakuBot"

  relaunch:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: Relaunch with new version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          passphrase: ${{ secrets.PROD_SSH_PASSPHRASE }}
          script: |
            cd OttakuBot
            tar -xvf com.example.stocks-aggregator-0.0.1.tar 
            sudo systemctl restart ottakubot.service